version = 0.1
[default.deploy.parameters]
stack_name = "playkosmos-registration"
resolve_s3 = false
s3_prefix = "playkosmos-bucket"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
