AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  registration-service

  Sample SAM Template for registration-service

Globals:
  Function:
    Timeout: 20
    MemorySize: 512
    Tracing: Active
    Environment:
      Variables:
        PARAM1: VALUE
        JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
  Api:
    TracingEnabled: true

Resources:
  #Registration Function
  RegistrationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: RegistrationFunction
      Handler: controller.RegisterController::handleRequest
      Runtime: java11
      Architectures:
      - x86_64
      Events:
        Registration:
          Type: Api
          Properties:
            Path: /register
            Method: POST
      Policies:
        - Statement:
            - Sid: SecretsManagerPermissions
              Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:playkosmos-database-yMWc77"
        - Statement:
            - Sid: LambdaInvokePermissions
              Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: !Sub "arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:playkosmos-notification-SendOTPFunction-AEHIGlD8aSnf"

Outputs:
  RetryApi:
    Description: API Gateway endpoint URL for Prod stage for Registration Validation function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/retry-otp"
  ValidationApi:
    Description: API Gateway endpoint URL for Prod stage for Registration Validation function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/verify-playmate"
  RegistrationApi:
    Description: API Gateway endpoint URL for Prod stage for Registration function
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/register"
